# Lista de 150 Pokemon para usar como nodos en estructuras de datos
pokemon_list = [
    {'numero': 448, 'nombre': 'Lucario', 'tipos': ['Lucha', 'Acero'], 'debilidades': ['Fuego', 'Lucha', 'Tierra'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 6, 'nombre': 'Charizard', 'tipos': ['Fuego', 'Volador'], 'debilidades': ['Agua', 'Eléctrico', 'Roca'], 'mega_evolucion': True, 'gigamax': True},
    {'numero': 25, 'nombre': 'Pikachu', 'tipos': ['Eléctrico'], 'debilidades': ['Tierra'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 906, 'nombre': 'Meowscarada', 'tipos': ['Planta', 'Siniestro'], 'debilidades': ['Fuego', 'Hielo', 'Lucha', 'Veneno', 'Bicho', 'Hada', 'Volador'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 392, 'nombre': 'Infernape', 'tipos': ['Fuego', 'Lucha'], 'debilidades': ['Agua', 'Psíquico', 'Volador', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 133, 'nombre': 'Eevee', 'tipos': ['Normal'], 'debilidades': ['Lucha'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 150, 'nombre': 'Mewtwo', 'tipos': ['Psíquico'], 'debilidades': ['Bicho', 'Siniestro', 'Fantasma'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 445, 'nombre': 'Garchomp', 'tipos': ['Dragón', 'Tierra'], 'debilidades': ['Hielo', 'Dragón', 'Hada'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 94, 'nombre': 'Gengar', 'tipos': ['Fantasma', 'Veneno'], 'debilidades': ['Tierra', 'Psíquico', 'Fantasma', 'Siniestro'], 'mega_evolucion': True, 'gigamax': True},
    {'numero': 778, 'nombre': 'Mimikyu', 'tipos': ['Fantasma', 'Hada'], 'debilidades': ['Fantasma', 'Acero'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 1, 'nombre': 'Bulbasaur', 'tipos': ['Planta', 'Veneno'], 'debilidades': ['Fuego', 'Hielo', 'Psíquico', 'Volador'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 658, 'nombre': 'Greninja', 'tipos': ['Agua', 'Siniestro'], 'debilidades': ['Planta', 'Eléctrico', 'Lucha', 'Bicho', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 143, 'nombre': 'Snorlax', 'tipos': ['Normal'], 'debilidades': ['Lucha'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 887, 'nombre': 'Dragapult', 'tipos': ['Dragón', 'Fantasma'], 'debilidades': ['Hielo', 'Dragón', 'Hada', 'Fantasma', 'Siniestro'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 384, 'nombre': 'Rayquaza', 'tipos': ['Dragón', 'Volador'], 'debilidades': ['Hielo', 'Roca', 'Dragón', 'Hada'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 130, 'nombre': 'Gyarados', 'tipos': ['Agua', 'Volador'], 'debilidades': ['Eléctrico', 'Roca'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 282, 'nombre': 'Gardevoir', 'tipos': ['Psíquico', 'Hada'], 'debilidades': ['Veneno', 'Fantasma', 'Acero'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 149, 'nombre': 'Dragonite', 'tipos': ['Dragón', 'Volador'], 'debilidades': ['Hielo', 'Roca', 'Dragón', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 545, 'nombre': 'Scolipede', 'tipos': ['Bicho', 'Veneno'], 'debilidades': ['Fuego', 'Psíquico', 'Volador', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 724, 'nombre': 'Decidueye', 'tipos': ['Planta', 'Fantasma'], 'debilidades': ['Fuego', 'Hielo', 'Volador', 'Fantasma', 'Siniestro'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 812, 'nombre': 'Rillaboom', 'tipos': ['Planta'], 'debilidades': ['Fuego', 'Hielo', 'Veneno', 'Volador', 'Bicho'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 376, 'nombre': 'Metagross', 'tipos': ['Acero', 'Psíquico'], 'debilidades': ['Fuego', 'Tierra', 'Fantasma', 'Siniestro'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 157, 'nombre': 'Typhlosion', 'tipos': ['Fuego'], 'debilidades': ['Agua', 'Tierra', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 257, 'nombre': 'Blaziken', 'tipos': ['Fuego', 'Lucha'], 'debilidades': ['Agua', 'Psíquico', 'Volador', 'Tierra'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 892, 'nombre': 'Urshifu (Single Strike)', 'tipos': ['Lucha', 'Siniestro'], 'debilidades': ['Lucha', 'Volador', 'Hada'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 181, 'nombre': 'Ampharos', 'tipos': ['Eléctrico'], 'debilidades': ['Tierra'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 937, 'nombre': 'Ceruledge', 'tipos': ['Fuego', 'Fantasma'], 'debilidades': ['Agua', 'Tierra', 'Roca', 'Fantasma', 'Siniestro'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 475, 'nombre': 'Gallade', 'tipos': ['Psíquico', 'Lucha'], 'debilidades': ['Volador', 'Fantasma', 'Hada'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 635, 'nombre': 'Hydreigon', 'tipos': ['Siniestro', 'Dragón'], 'debilidades': ['Hada', 'Lucha', 'Bicho', 'Hielo', 'Dragón'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 12, 'nombre': 'Butterfree', 'tipos': ['Bicho', 'Volador'], 'debilidades': ['Fuego', 'Eléctrico', 'Hielo', 'Volador', 'Roca'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 248, 'nombre': 'Tyranitar', 'tipos': ['Roca', 'Siniestro'], 'debilidades': ['Lucha', 'Tierra', 'Bicho', 'Acero', 'Agua', 'Planta', 'Hada'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 700, 'nombre': 'Sylveon', 'tipos': ['Hada'], 'debilidades': ['Veneno', 'Acero'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 389, 'nombre': 'Torterra', 'tipos': ['Planta', 'Tierra'], 'debilidades': ['Fuego', 'Hielo', 'Volador', 'Bicho'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 815, 'nombre': 'Cinderace', 'tipos': ['Fuego'], 'debilidades': ['Agua', 'Tierra', 'Roca'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 9, 'nombre': 'Blastoise', 'tipos': ['Agua'], 'debilidades': ['Planta', 'Eléctrico'], 'mega_evolucion': True, 'gigamax': True},
    {'numero': 609, 'nombre': 'Chandelure', 'tipos': ['Fantasma', 'Fuego'], 'debilidades': ['Agua', 'Tierra', 'Roca', 'Fantasma', 'Siniestro'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 197, 'nombre': 'Umbreon', 'tipos': ['Siniestro'], 'debilidades': ['Lucha', 'Bicho', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 254, 'nombre': 'Sceptile', 'tipos': ['Planta'], 'debilidades': ['Fuego', 'Hielo', 'Veneno', 'Volador', 'Bicho'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 483, 'nombre': 'Dialga', 'tipos': ['Acero', 'Dragón'], 'debilidades': ['Lucha', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 727, 'nombre': 'Incineroar', 'tipos': ['Fuego', 'Siniestro'], 'debilidades': ['Agua', 'Lucha', 'Tierra', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 405, 'nombre': 'Luxray', 'tipos': ['Eléctrico'], 'debilidades': ['Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 849, 'nombre': 'Toxtricity (Amped)', 'tipos': ['Eléctrico', 'Veneno'], 'debilidades': ['Tierra', 'Psíquico'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 3, 'nombre': 'Venusaur', 'tipos': ['Planta', 'Veneno'], 'debilidades': ['Fuego', 'Hielo', 'Psíquico', 'Volador'], 'mega_evolucion': True, 'gigamax': True},
    {'numero': 260, 'nombre': 'Swampert', 'tipos': ['Agua', 'Tierra'], 'debilidades': ['Planta'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 571, 'nombre': 'Zoroark', 'tipos': ['Siniestro'], 'debilidades': ['Lucha', 'Bicho', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 154, 'nombre': 'Meganium', 'tipos': ['Planta'], 'debilidades': ['Fuego', 'Hielo', 'Veneno', 'Volador', 'Bicho'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 334, 'nombre': 'Altaria', 'tipos': ['Dragón', 'Volador'], 'debilidades': ['Hielo', 'Roca', 'Dragón', 'Hada'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 79, 'nombre': 'Slowpoke', 'tipos': ['Agua', 'Psíquico'], 'debilidades': ['Planta', 'Eléctrico', 'Bicho', 'Fantasma', 'Siniestro'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 989, 'nombre': 'Sandy Shocks', 'tipos': ['Eléctrico', 'Tierra'], 'debilidades': ['Agua', 'Planta', 'Hielo', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 134, 'nombre': 'Vaporeon', 'tipos': ['Agua'], 'debilidades': ['Planta', 'Eléctrico'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 468, 'nombre': 'Togekiss', 'tipos': ['Hada', 'Volador'], 'debilidades': ['Eléctrico', 'Hielo', 'Veneno', 'Roca', 'Acero'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 212, 'nombre': 'Scizor', 'tipos': ['Bicho', 'Acero'], 'debilidades': ['Fuego'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 68, 'nombre': 'Machamp', 'tipos': ['Lucha'], 'debilidades': ['Psíquico', 'Volador', 'Hada'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 668, 'nombre': 'Pyroar', 'tipos': ['Fuego', 'Normal'], 'debilidades': ['Agua', 'Lucha', 'Tierra', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 1004, 'nombre': 'Chi-Yu', 'tipos': ['Siniestro', 'Fuego'], 'debilidades': ['Agua', 'Lucha', 'Tierra', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 487, 'nombre': 'Giratina (Origin)', 'tipos': ['Fantasma', 'Dragón'], 'debilidades': ['Hielo', 'Dragón', 'Hada', 'Fantasma', 'Siniestro'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 823, 'nombre': 'Corviknight', 'tipos': ['Volador', 'Acero'], 'debilidades': ['Fuego', 'Eléctrico'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 160, 'nombre': 'Feraligatr', 'tipos': ['Agua'], 'debilidades': ['Planta', 'Eléctrico'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 306, 'nombre': 'Aggron', 'tipos': ['Acero', 'Roca'], 'debilidades': ['Lucha', 'Tierra', 'Agua'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 707, 'nombre': 'Klefki', 'tipos': ['Acero', 'Hada'], 'debilidades': ['Fuego', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 503, 'nombre': 'Samurott', 'tipos': ['Agua'], 'debilidades': ['Planta', 'Eléctrico'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 970, 'nombre': 'Glimmora', 'tipos': ['Roca', 'Veneno'], 'debilidades': ['Tierra', 'Psíquico', 'Acero', 'Agua'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 229, 'nombre': 'Houndoom', 'tipos': ['Siniestro', 'Fuego'], 'debilidades': ['Agua', 'Lucha', 'Tierra', 'Roca'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 809, 'nombre': 'Melmetal', 'tipos': ['Acero'], 'debilidades': ['Fuego', 'Lucha', 'Tierra'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 359, 'nombre': 'Absol', 'tipos': ['Siniestro'], 'debilidades': ['Lucha', 'Bicho', 'Hada'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 1000, 'nombre': 'Gholdengo', 'tipos': ['Acero', 'Fantasma'], 'debilidades': ['Fuego', 'Tierra', 'Fantasma', 'Siniestro'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 745, 'nombre': 'Lycanroc (Midday)', 'tipos': ['Roca'], 'debilidades': ['Agua', 'Planta', 'Lucha', 'Tierra', 'Acero'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 461, 'nombre': 'Weavile', 'tipos': ['Siniestro', 'Hielo'], 'debilidades': ['Lucha', 'Roca', 'Bicho', 'Acero', 'Fuego', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 123, 'nombre': 'Scyther', 'tipos': ['Bicho', 'Volador'], 'debilidades': ['Fuego', 'Eléctrico', 'Hielo', 'Volador', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 65, 'nombre': 'Alakazam', 'tipos': ['Psíquico'], 'debilidades': ['Bicho', 'Siniestro', 'Fantasma'], 'mega_evolucion': True, 'gigamax': True},
    {'numero': 530, 'nombre': 'Excadrill', 'tipos': ['Tierra', 'Acero'], 'debilidades': ['Fuego', 'Agua', 'Lucha', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 834, 'nombre': 'Drednaw', 'tipos': ['Agua', 'Roca'], 'debilidades': ['Planta', 'Eléctrico', 'Lucha', 'Tierra'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 373, 'nombre': 'Salamence', 'tipos': ['Dragón', 'Volador'], 'debilidades': ['Hielo', 'Roca', 'Dragón', 'Hada'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 923, 'nombre': 'Pawmot', 'tipos': ['Eléctrico', 'Lucha'], 'debilidades': ['Tierra', 'Psíquico', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 715, 'nombre': 'Noivern', 'tipos': ['Volador', 'Dragón'], 'debilidades': ['Hielo', 'Roca', 'Dragón', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 196, 'nombre': 'Espeon', 'tipos': ['Psíquico'], 'debilidades': ['Bicho', 'Siniestro', 'Fantasma'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 310, 'nombre': 'Manectric', 'tipos': ['Eléctrico'], 'debilidades': ['Tierra'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 500, 'nombre': 'Emboar', 'tipos': ['Fuego', 'Lucha'], 'debilidades': ['Agua', 'Psíquico', 'Volador', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 818, 'nombre': 'Inteleon', 'tipos': ['Agua'], 'debilidades': ['Planta', 'Eléctrico'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 214, 'nombre': 'Heracross', 'tipos': ['Bicho', 'Lucha'], 'debilidades': ['Fuego', 'Psíquico', 'Volador', 'Hada'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 44, 'nombre': 'Gloom', 'tipos': ['Planta', 'Veneno'], 'debilidades': ['Fuego', 'Hielo', 'Psíquico', 'Volador'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 959, 'nombre': 'Tinkaton', 'tipos': ['Hada', 'Acero'], 'debilidades': ['Fuego', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 395, 'nombre': 'Empoleon', 'tipos': ['Agua', 'Acero'], 'debilidades': ['Eléctrico', 'Lucha', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 798, 'nombre': 'Kartana', 'tipos': ['Planta', 'Acero'], 'debilidades': ['Fuego', 'Lucha'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 625, 'nombre': 'Bisharp', 'tipos': ['Siniestro', 'Acero'], 'debilidades': ['Lucha', 'Fuego', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 879, 'nombre': 'Copperajah', 'tipos': ['Acero'], 'debilidades': ['Fuego', 'Lucha', 'Tierra'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 135, 'nombre': 'Jolteon', 'tipos': ['Eléctrico'], 'debilidades': ['Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 330, 'nombre': 'Flygon', 'tipos': ['Tierra', 'Dragón'], 'debilidades': ['Hielo', 'Dragón', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 914, 'nombre': 'Quaquaval', 'tipos': ['Agua', 'Lucha'], 'debilidades': ['Planta', 'Eléctrico', 'Psíquico', 'Volador', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 491, 'nombre': 'Darkrai', 'tipos': ['Siniestro'], 'debilidades': ['Lucha', 'Bicho', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 719, 'nombre': 'Diancie', 'tipos': ['Roca', 'Hada'], 'debilidades': ['Acero', 'Planta', 'Agua', 'Tierra'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 230, 'nombre': 'Kingdra', 'tipos': ['Agua', 'Dragón'], 'debilidades': ['Dragón', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 59, 'nombre': 'Arcanine', 'tipos': ['Fuego'], 'debilidades': ['Agua', 'Tierra', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 675, 'nombre': 'Pangoro', 'tipos': ['Lucha', 'Siniestro'], 'debilidades': ['Lucha', 'Volador', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 839, 'nombre': 'Coalossal', 'tipos': ['Roca', 'Fuego'], 'debilidades': ['Agua', 'Tierra', 'Lucha', 'Roca'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 36, 'nombre': 'Clefable', 'tipos': ['Hada'], 'debilidades': ['Veneno', 'Acero'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 1007, 'nombre': 'Koraidon', 'tipos': ['Lucha', 'Dragón'], 'debilidades': ['Hada', 'Volador', 'Psíquico', 'Hielo', 'Dragón'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 128, 'nombre': 'Tauros', 'tipos': ['Normal'], 'debilidades': ['Lucha'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 208, 'nombre': 'Steelix', 'tipos': ['Acero', 'Tierra'], 'debilidades': ['Fuego', 'Agua', 'Lucha', 'Tierra'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 766, 'nombre': 'Passimian', 'tipos': ['Lucha'], 'debilidades': ['Psíquico', 'Volador', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 454, 'nombre': 'Toxicroak', 'tipos': ['Veneno', 'Lucha'], 'debilidades': ['Psíquico', 'Volador', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 95, 'nombre': 'Onix', 'tipos': ['Roca', 'Tierra'], 'debilidades': ['Agua', 'Planta', 'Lucha', 'Tierra', 'Acero', 'Hielo'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 890, 'nombre': 'Eternatus', 'tipos': ['Veneno', 'Dragón'], 'debilidades': ['Tierra', 'Psíquico', 'Hielo', 'Dragón'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 382, 'nombre': 'Kyogre', 'tipos': ['Agua'], 'debilidades': ['Planta', 'Eléctrico'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 555, 'nombre': 'Darmanitan (Standard)', 'tipos': ['Fuego'], 'debilidades': ['Agua', 'Tierra', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 142, 'nombre': 'Aerodactyl', 'tipos': ['Roca', 'Volador'], 'debilidades': ['Agua', 'Eléctrico', 'Hielo', 'Roca', 'Acero'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 706, 'nombre': 'Goodra', 'tipos': ['Dragón'], 'debilidades': ['Hielo', 'Dragón', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 911, 'nombre': 'Skeledirge', 'tipos': ['Fuego', 'Fantasma'], 'debilidades': ['Agua', 'Tierra', 'Roca', 'Fantasma', 'Siniestro'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 286, 'nombre': 'Breloom', 'tipos': ['Planta', 'Lucha'], 'debilidades': ['Fuego', 'Hielo', 'Veneno', 'Psíquico', 'Volador', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 478, 'nombre': 'Froslass', 'tipos': ['Hielo', 'Fantasma'], 'debilidades': ['Fuego', 'Roca', 'Fantasma', 'Siniestro', 'Acero'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 800, 'nombre': 'Necrozma', 'tipos': ['Psíquico'], 'debilidades': ['Bicho', 'Siniestro', 'Fantasma'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 136, 'nombre': 'Flareon', 'tipos': ['Fuego'], 'debilidades': ['Agua', 'Tierra', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 302, 'nombre': 'Sableye', 'tipos': ['Siniestro', 'Fantasma'], 'debilidades': ['Hada'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 612, 'nombre': 'Haxorus', 'tipos': ['Dragón'], 'debilidades': ['Hielo', 'Dragón', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 884, 'nombre': 'Duraludon', 'tipos': ['Acero', 'Dragón'], 'debilidades': ['Lucha', 'Tierra'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 42, 'nombre': 'Golbat', 'tipos': ['Veneno', 'Volador'], 'debilidades': ['Eléctrico', 'Hielo', 'Psíquico', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 245, 'nombre': 'Suicune', 'tipos': ['Agua'], 'debilidades': ['Planta', 'Eléctrico'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 784, 'nombre': 'Kommo-o', 'tipos': ['Dragón', 'Lucha'], 'debilidades': ['Hada', 'Psíquico', 'Volador', 'Hielo', 'Dragón'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 121, 'nombre': 'Starmie', 'tipos': ['Agua', 'Psíquico'], 'debilidades': ['Planta', 'Eléctrico', 'Bicho', 'Fantasma', 'Siniestro'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 560, 'nombre': 'Scrafty', 'tipos': ['Siniestro', 'Lucha'], 'debilidades': ['Lucha', 'Volador', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 983, 'nombre': 'Kingambit', 'tipos': ['Siniestro', 'Acero'], 'debilidades': ['Lucha', 'Fuego', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 354, 'nombre': 'Banette', 'tipos': ['Fantasma'], 'debilidades': ['Fantasma', 'Siniestro'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 472, 'nombre': 'Gliscor', 'tipos': ['Tierra', 'Volador'], 'debilidades': ['Agua', 'Hielo'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 851, 'nombre': 'Centiskorch', 'tipos': ['Fuego', 'Bicho'], 'debilidades': ['Agua', 'Volador', 'Roca'], 'mega_evolucion': False, 'gigamax': True},
    {'numero': 1008, 'nombre': 'Miraidon', 'tipos': ['Eléctrico', 'Dragón'], 'debilidades': ['Tierra', 'Hielo', 'Dragón', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 722, 'nombre': 'Rowlet', 'tipos': ['Planta', 'Volador'], 'debilidades': ['Fuego', 'Hielo', 'Veneno', 'Volador', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 249, 'nombre': 'Lugia', 'tipos': ['Psíquico', 'Volador'], 'debilidades': ['Eléctrico', 'Hielo', 'Roca', 'Fantasma', 'Siniestro'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 383, 'nombre': 'Groudon', 'tipos': ['Tierra'], 'debilidades': ['Agua', 'Planta', 'Hielo'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 620, 'nombre': 'Mienshao', 'tipos': ['Lucha'], 'debilidades': ['Psíquico', 'Volador', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 888, 'nombre': 'Zacian (Crowned)', 'tipos': ['Hada', 'Acero'], 'debilidades': ['Fuego', 'Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 185, 'nombre': 'Sudowoodo', 'tipos': ['Roca'], 'debilidades': ['Agua', 'Planta', 'Lucha', 'Tierra', 'Acero'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 466, 'nombre': 'Electivire', 'tipos': ['Eléctrico'], 'debilidades': ['Tierra'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 77, 'nombre': 'Ponyta', 'tipos': ['Fuego'], 'debilidades': ['Agua', 'Tierra', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 289, 'nombre': 'Slaking', 'tipos': ['Normal'], 'debilidades': ['Lucha'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 741, 'nombre': 'Oricorio (Baile)', 'tipos': ['Fuego', 'Volador'], 'debilidades': ['Agua', 'Eléctrico', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 553, 'nombre': 'Krookodile', 'tipos': ['Tierra', 'Siniestro'], 'debilidades': ['Agua', 'Planta', 'Hielo', 'Lucha', 'Bicho', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 964, 'nombre': 'Palafin (Hero)', 'tipos': ['Agua'], 'debilidades': ['Planta', 'Eléctrico'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 430, 'nombre': 'Honchkrow', 'tipos': ['Siniestro', 'Volador'], 'debilidades': ['Eléctrico', 'Hielo', 'Roca', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 144, 'nombre': 'Articuno', 'tipos': ['Hielo', 'Volador'], 'debilidades': ['Fuego', 'Eléctrico', 'Roca', 'Acero'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 644, 'nombre': 'Zekrom', 'tipos': ['Dragón', 'Eléctrico'], 'debilidades': ['Tierra', 'Hielo', 'Dragón', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 250, 'nombre': 'Ho-Oh', 'tipos': ['Fuego', 'Volador'], 'debilidades': ['Agua', 'Eléctrico', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 80, 'nombre': 'Slowbro', 'tipos': ['Agua', 'Psíquico'], 'debilidades': ['Planta', 'Eléctrico', 'Bicho', 'Fantasma', 'Siniestro'], 'mega_evolucion': True, 'gigamax': False},
    {'numero': 789, 'nombre': 'Cosmog', 'tipos': ['Psíquico'], 'debilidades': ['Bicho', 'Siniestro', 'Fantasma'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 398, 'nombre': 'Staraptor', 'tipos': ['Normal', 'Volador'], 'debilidades': ['Eléctrico', 'Hielo', 'Roca'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 646, 'nombre': 'Kyurem', 'tipos': ['Dragón', 'Hielo'], 'debilidades': ['Lucha', 'Roca', 'Acero', 'Dragón', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 875, 'nombre': 'Eiscue (Ice Face)', 'tipos': ['Hielo'], 'debilidades': ['Fuego', 'Lucha', 'Roca', 'Acero'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 493, 'nombre': 'Arceus', 'tipos': ['Normal'], 'debilidades': ['Lucha'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 115, 'nombre': 'Kangaskhan', 'tipos': ['Normal'], 'debilidades': ['Lucha'], 'mega_evolucion': True, 'gigamax': True},
    {'numero': 717, 'nombre': 'Yveltal', 'tipos': ['Siniestro', 'Volador'], 'debilidades': ['Eléctrico', 'Hielo', 'Roca', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
    {'numero': 697, 'nombre': 'Tyrantrum', 'tipos': ['Roca', 'Dragón'], 'debilidades': ['Hielo', 'Lucha', 'Tierra', 'Dragón', 'Acero', 'Hada'], 'mega_evolucion': False, 'gigamax': False},
]